id: P007998
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG535
  title: དྲན་པའི་ཟིན་ཐོ
  author: ''
  volumes:
    18bb0941a4014db8805a3a7a420cffec:
      image_group_id: I1KG544
      title: ''
      volume_number: 1
      total_pages: 110
ebook_metadata:
  title: དྲན་པའི་ཟིན་ཐོ
  author: ''
  sku: P007998
  cover: cover.jpg
  layers:
  - pagination
