id: P007998
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:54:10.250976
source_metadata:
  id: bdr:W1KG535
  title: དྲན་པའི་ཟིན་ཐོ
  author: ''
  volumes:
    c9187e7ddc5e4cb6802a677fda93f3e5:
      image_group_id: I1KG544
      title: Volume 1 of dran pa'i zin tho
      volume_number: 1
      total_pages: 110
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
