id: I2E37BAAE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:25:19+00:00'
last_modified: '2022-06-09T08:28:34.461418+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG535
  title: དྲན་པའི་ཟིན་ཐོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6616':
      image_group_id: I1KG544
      title: Volume 1 of dran pa'i zin tho
      total_pages: 110
      order: 1
      base_file: 6616.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
